### ISSUE TITLE
RuntimeException: Join Failed

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon-ibex#247]
Where does the exception occur? -> CompanyToIT.cc.TestSimplePositive.testCompany

---

What happens? -> java.lang.RuntimeException: Join failed

---
Reason? -> At the moment we have no clue why this occurs but it never happens for ModelGen

---

Here the complete stacktrace:
```
java.lang.RuntimeException: Join failed
	at org.gervarro.democles.interpreter.incremental.rete.RetePatternMatcherModule.performIncrementalUpdates(RetePatternMatcherModule.java:117)
	at org.emoflon.ibex.tgg.runtime.engine.DemoclesEngine.updateMatches(DemoclesEngine.java:504)
	at org.emoflon.ibex.tgg.operational.OperationalStrategy.run(OperationalStrategy.java:241)
	at testsuite.ibex.testUtil.CCTestCase.runGenerator(CCTestCase.java:11)
	at testsuite.ibex.CompanyToIT.cc.TestSimplePositive.testCompany(TestSimplePositive.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
Caused by: java.lang.RuntimeException: Join failed
	at org.gervarro.democles.runtime.JoinOperation.handleIncrementalJoin(JoinOperation.java:53)
	at org.gervarro.democles.runtime.JoinOperation.execute(JoinOperation.java:43)
	at org.gervarro.democles.runtime.EventHandlingTask.perform(EventHandlingTask.java:37)
	at org.gervarro.democles.common.runtime.Session.run(Session.java:34)
	at org.gervarro.democles.runtime.IncrementalUpdateSession.call(IncrementalUpdateSession.java:143)
	at org.gervarro.democles.interpreter.incremental.rete.RetePatternMatcherModule.performIncrementalUpdates(RetePatternMatcherModule.java:115)
	... 28 more

```

**Comment by gervarro** [comment]
This issue seems to be fixed now. The fix will be available together with the other ones.
